//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demka_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int idComment { get; set; }
        public string message { get; set; }
        public int idUser { get; set; }
        public int idReguest { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Users Users { get; set; }
    }
}
