//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demka_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int isRequest { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<int> idclimateTechType { get; set; }
        public string climateTechModel { get; set; }
        public string problemDescryption { get; set; }
        public Nullable<int> idRequestStatus { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> idMaster { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual climateTechTypes climateTechTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual requestStatus requestStatus { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
     
    }
}
